### ISSUE TITLE
GitHub Actions for Continuous Integration (CI)

### ISSUE THREAD

**Issue by neoblizz** [gunrock/essentials#32]
GitHub Actions (https://github.com/gunrock/essentials/actions/new) supports C++/Cmake really well, but we need to see if we can get GPU support working with it for essentials.

**Comment by aktech** [comment]
Hi @neoblizz I am the creator of Cirun.io, "GPU" and "CI" caught my eye.

FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/

It is used in multiple open source projects needing GPU support like the following:

https://github.com/pystatgen/sgkit/
https://github.com/qutip/qutip-cupy

It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.

Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)

**Comment by neoblizz** [comment]
> Hi @neoblizz I am the creator of Cirun.io, "GPU" and "CI" caught my eye.
> 
> FWIW I'll share my two cents. I created a service for problems like these, which is basically running custom machines (including GPUs) in GitHub Actions: https://cirun.io/
> 
> It is used in multiple open source projects needing GPU support like the following:
> 
> https://github.com/pystatgen/sgkit/
> https://github.com/qutip/qutip-cupy
> 
> It is fairly simple to setup, all you need is a cloud account (AWS or GCP) and a simple yaml file describing what kind of machines you need and Cirun will spin up ephemeral machines on your cloud for GitHub Actions to run. It's native to GitHub ecosystem, which mean you can see logs/trigger in the Github's interface itself, just like any Github Action run.
> 
> Also, note that Cirun is free for Open source projects. (You only pay to your cloud provider for machine usage)

I'll definitely take a look! Thank you for bringing this to my attention.

**Comment by aktech** [comment]
No worries, feel free to ping me if you need any help or have any questions.

**Comment by neoblizz** [comment]
Ended up setting up something simple for CUDA-build testing; https://github.com/gunrock/essentials/actions/runs/1570781390

**Comment by neoblizz** [comment]
Saving windows workflow for later, here.
```yml
# Gunrock/Essentials Windows Workflow
name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master and dev branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Fetch CUDA toolkit using Jimver/cuda-toolkit@v0.2.5
      - name: Fetch CUDA toolkit
        uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
          linux-local-args: '["--toolkit"]'

      # Runs a single command using the runners shell
      - name: Check nvcc version
        run: nvcc -V
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure cmake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -D ESSENTIALS_BUILD_TESTS=ON #-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
        
      - name: Build all applications
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
        
        # TODO: Use the following once we have BUILD_TYPE and envrionment variables set-up:
        # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
```
